language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- export BUILD_LIFE=${TRAVIS_COMMIT:0:7}
- ant run-tests
script:
- ant -DbuildLife=${BUILD_LIFE}
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
